### ISSUE TITLE
Sundials Matlab Interface compatibility

### ISSUE THREAD

**Issue by lionsimbatoolbox** [lionsimbatoolbox/LIONSIMBA#1]
According to SUNDIALS home page ([http://computation.llnl.gov/projects/sundials/sundials-software](url)), the interface of the numerical integrator IDA for the Matlab environment (named sundialsTB) has been removed from the latest version of the software. The latest version of sundials supporting the Matlab interface is the 2.6.2 (Available here [http://computation.llnl.gov/projects/sundials/download/sundials-2.6.2.tar.gz](url)).

Future releases of LIONSIMBA will support the use of different numerical integrators to avoid possible incompatibilities with the newest versions of the IDA integrator and the Matlab environment.

Thanks to Krishnakumar  Gopalakrishnan for pointing out the issue.

**Comment by lionsimbatoolbox** [comment]
User's manual updated with required information

**Comment by Bala-2318** [comment]
[http://computation.llnl.gov/projects/sundials/download/sundials-2.6.2.tar.gz](https://github.com/lionsimbatoolbox/LIONSIMBA/issues/url))., is this not available right now? How to install sundials in the Matlab R2022a?
