### ISSUE TITLE
Bug in ionicFlux.m

### ISSUE THREAD

**Issue by sarasyha** [lionsimbatoolbox/LIONSIMBA#11]
Line 33: deltap = ((0.5*param.F)./(param.R*T(param.Nal+1:param.Nal+param.Np))).*(Phis(1:param.Np)-Phie(1:param.Np)-U_p); 
should be:
Line 33: deltap = ((0.5*param.R)./(param.F*T(param.Nal+1:param.Nal+param.Np))).*(Phis(1:param.Np)-Phie(1:param.Np)-U_p); 

Same for Line 47 for deltan

**Comment by lionsimbatoolbox** [comment]
The implemented code is right. It follows the equation for the ionic flux. Apparently there is a typo in the related LIONSIMBA paper. This will be pointed out in the README.md file.
