### ISSUE TITLE
User's Manual_2018

### ISSUE THREAD

**Issue by JannBorli** [lionsimbatoolbox/LIONSIMBA#12]
Dear Sir or Madam,

i found a little mistake in your manual.

The link to MinGW-w64 provided in chapter 1.2.1:

https://it.mathworks.com/matlabcentral/fileexchange/\52848-matlab-support-for-mingw-w64-c-c+
+-compiler

is incorret. The backslash should be removed to get:

https://it.mathworks.com/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c+
+-compiler

The link to the SUNDIALS download page also changed.
To get the corosponding version of SUNDIALS go to:
https://computing.llnl.gov/projects/sundials/sundials-software

Thank you in advandce and thank you for providing a tool like this.

Yours sincerelly 

Jann

**Comment by lionsimbatoolbox** [comment]
Hi Jann,

thanks a lot for pointing this out. I'll take care and fix the links in the Wiki. Actually the pdf manual is quite old, and the Wiki should be followed instead. 

Thanks

**Comment by lionsimbatoolbox** [comment]
PDF file removed and fixed wiki links
