### ISSUE TITLE
Bug in startSimulation.m?

### ISSUE THREAD

**Issue by sarasyha** [lionsimbatoolbox/LIONSIMBA#13]
Line 234: start_xp_index  = n_diff(i)+n_alg(i)+start_xp_index;
should be
Line 234: start_xp_index  =  n_diff(i)+start_xp_index;
?
Since xp is the index for differential variables, I think we shouldn't have n_alg(i)...

**Comment by lionsimbatoolbox** [comment]
According to the way variables are stored it is required to sum both the differential and algebraic ones.
