### ISSUE TITLE
LIONSIMBA paper performance comparisons

### ISSUE THREAD

**Issue by hanrach** [lionsimbatoolbox/LIONSIMBA#14]
Hi,

Thanks for developing this MATLAB toolbox for the p2d models.
I have a question about Table VIII in the paper (it compares the performance between LIONSIMBA, DUALFOIL and COMSOL). Are the LIONSIMBA simulations run with the full order solid phase diffusion model or the two parameter/ three parameter approximation model ?

**Comment by lionsimbatoolbox** [comment]
Hi!
The comparison was carried out considering the models in the same conditions, and therefore the full-order (Fick's) model was used in all the simulations.
