### ISSUE TITLE
Unrecognized function or variable 'cvm_ok'.

### ISSUE THREAD

**Issue by Raviiisc** [lionsimbatoolbox/LIONSIMBA#16]
I am getting the following error while running the Sundial "install_STB.m" file. I am using 2020b version of Matlab. Could this be rectified?

**Comment by lionsimbatoolbox** [comment]
This may be very specific for Sundials installation; are you able to test it over a different version of Matlab?

**Comment by Raviiisc** [comment]
I didn't try it on other versions. What is the version that it works on ?

**Comment by lionsimbatoolbox** [comment]
I don't recall all the versions it has been used on; it should work from Matlab 2014/2015 onward. There was a similar issue in #issue3, but the user seems to have resolved the problem by moving machine. I believe it may be something related to the configuration of the compiler for Matlab.

**Comment by HelloJunyang** [comment]
@Raviiisc 
1. Launch matlab in sundialsTB (folder)
% cd srcdir/sundialsTB
% matlab
2. Run the matlab script install STB

**Comment by Raviiisc** [comment]
Hi Junyang,
     Thank you so much brother. The issue got resolved. I am so grateful to you for commenting it out and ending my struggle to run the code.
      
Thanks and regards,
Ravi

**Comment by lionsimbatoolbox** [comment]
Thanks @HelloJunyang for the help! I'm closing the issue.
