### ISSUE TITLE
Cutoff current condition for CV mode

### ISSUE THREAD

**Issue by BeautifulBeer** [lionsimbatoolbox/LIONSIMBA#17]
Hi, Thank you for the nice project.
Is it available in LIONSIMBA to terminate CV simulation in the middle by the cutoff current condition? I could not find the related examples or properties in the "Parameter" object.

**Comment by lionsimbatoolbox** [comment]
Hello!

Are you looking to terminate the simulation when the current reaches a specific value?

**Comment by BeautifulBeer** [comment]
Yes, Although I already solved this problem by modifying "checkSimulationStopConditions.m",  "startSimulation.m", and "Parameters_init.m", I was wondering if there is an official function for the mentioned issue.

**Comment by lionsimbatoolbox** [comment]
No, it was never considered a cutoff event as a function of the current.

**Comment by BeautifulBeer** [comment]
Thank you to inform me and I will close this issue.
