### ISSUE TITLE
Changing Chemistry

### ISSUE THREAD

**Issue by gj2002** [lionsimbatoolbox/LIONSIMBA#19]
What are the things to be kept in mind while changing/simulating for a new chemistry on LIONSIMBA?

**Comment by lionsimbatoolbox** [comment]
In principle all the parameters of the simulation should be changed to reflect the new chemistry. By new parameters, I mean the static ones (i.e., the ones defined as constant in the Parameters_init script), as well as all of those properties (e.g., OCV, electrolyte diffusion coefficient, etc.) that have a dependency on the state(s) of the cell.
