### ISSUE TITLE
solidPhasePotential equation in the boundary

### ISSUE THREAD

**Issue by freeyyc** [lionsimbatoolbox/LIONSIMBA#2]
I have met a problem, In the solidPhasePotential function , I trace it,and got this result(the first solidPhasePotential equation DAE ):
SX(((x_71-x_70)-((8e-005*(0.1*((683128*x_50)-x_120)))/59)))
But when I use myself method to discretization the solidPhasePotential equation, I have got another result:
SX(@1=8e-006, ((59*((x_71-x_70)/@1))-(((@1*(8.5391e+010*x_50))/2)-x_120)))

I think I have found the reason, is in following picture:
[picture link](http://note.youdao.com/noteshare?id=e07078153bb59f12c09b6bad52b83549&sub=7F3CA9EE0FE14703B3B2A1063F49B29C)

**Comment by martorchio** [comment]
Hi,

the question is not really clear. However, the first equation you  posted (the one provided by LIONSIMBA) seems to reflect the one you have posted on the attached note.
