### ISSUE TITLE
error in startsimulation.m

### ISSUE THREAD

**Issue by tharani001** [lionsimbatoolbox/LIONSIMBA#20]
The specified superclass 'SwigRef' contains a parse error, cannot be found on MATLAB's search path, or is shadowed by
another file with the same name.

Error in startSimulation>mainCore (line 318)
    xsym    = SX.sym('x',[sum(n_diff)+sum(n_alg),1]);

Error in startSimulation (line 107)
results = mainCore(t0,tf,initialState,input_density,param);

How to fix this error?

**Comment by lionsimbatoolbox** [comment]
SwigRef is referred generally to CasADi. Please make sure to have it installed properly. The Wiki provides information on the installation process, along with video tutorials on Youtube (linked in the wiki as well)
