### ISSUE TITLE
Rewriting parameters

### ISSUE THREAD

**Issue by gj2002** [lionsimbatoolbox/LIONSIMBA#21]
I created a user-defined function that runs on LIONSIMBA, which had to be invoked in another script. The function, after calling the parameters_init file into param, rewrites/overrides certain parameter values using the dot operator. 

Now when I run the script I wanted to, the following error appears:

Error using idm
Error using ==> IDAInitialSetup
y0 fails to satisfy constraints.
Error in IDACalcIC (line 76)
  [status, yy, yp] = idm(mode, tout, icmeth);
Error in startSimulation>mainCore (line 396)
[~, yy, ~] = IDACalcIC(t0+10,'FindAlgebraic');
Error in startSimulation (line 107)
results = mainCore(t0,tf,initialState,input_density,param);

To verify whether it was a syntax error, the user-defined function was run by supplying the necessary arguments from the command window, and the function ran properly without any errors and returned the expected value as well. When the same arguments are run, by accessing it from another script, the error appears. To verify the validity of the script, the script was run by calling the function, this time without overwriting parameters in the function, and this seemed to run. Kindly debug the issue if possible.

**Comment by lionsimbatoolbox** [comment]
Hello,

when working with DAEs, the solver needs to find the so-called "set of consistent initial conditions". The finding of such set may become challenging (or even infeasible) if some parameters are ill-conditioning the problem. Based on the error you're getting, it seems that the parameterization you're using is causing the issue.

**Comment by gj2002** [comment]
I identified the possibility of that being the case, but again as I mentioned, when running the function using the same parameters, and the same set of overriding statements, it seemed to run perfectly fine. In fact, the attempt was made such that when I overwrite certain parameters after calling parameters_init into a param structure; the dependent parameters are not influenced by these changes (eg. if cs_max is changed after calling parameters, the change in cs_init will not be reflected until that is also changed). The function I defined was such that it first overrides an independent parameter in parameters_init, and then using that, updates the dependent variables as well.

When run stand-alone by manually passing values, it works fine. But when the overriding of independent parameters is done via a function call from another script, the above error appears. Since it works standalone, I think the passed-on parameters give Consistent Initial Conditions. Is there any other possibility for such an error?

**Comment by lionsimbatoolbox** [comment]
I believe the tests you've been carrying out are not 100% representative of what happens when the code breaks. If they were exactly the same, they should work (the code here is deterministic).

Without knowing the code you wrote it is difficult to debug properly (I can't support here). However, this issue has to do with some bad parameterization which renders impossible to the solver to find a set of CIC. This could happen either before you start the simulation, or even when you cyclically call the simulator.

I would suggest you to deeply debug your code (both the working example and the one that is not working) to see for differences. There must be.

**Comment by gj2002** [comment]
The script referred to uses the optimisation toolbox of MATLAB. It was verified with other normal scripts that the above-mentioned parameterization works fine, and the error contributed was perhaps due to constraint-based readjustment of parameters.
Thank you for the assistance.
