### ISSUE TITLE
Definition of output variable results.Q in startSimulation.m

### ISSUE THREAD

**Issue by SharonSi1005** [lionsimbatoolbox/LIONSIMBA#23]
Dear developer,

Thanks very much for your great effort on this amazing toolbox. 

I have a question about the output variable results.Q in _startSimulation.m_. There is no description for this variable (so are results.dudtp and results.dudtn) and its value is always 0 after running the given example. I wonder if it is charging/discharging capacity. Can you please give a description of this variable?

Best regards,
Sharon

**Comment by lionsimbatoolbox** [comment]
Hello,

thanks for your message. That variable was introduced in a later version of the code. You can find more information by reading this [paper](https://www.researchgate.net/profile/Dm-Raimondo/publication/300076370_Optimal_Health-aware_Charging_Protocol_for_Lithium-ion_Batteries_A_Fast_Model_Predictive_Control_Approach/links/5c118f374585157ac1be1689/Optimal-Health-aware-Charging-Protocol-for-Lithium-ion-Batteries-A-Fast-Model-Predictive-Control-Approach.pdf).

Variables like dudt (which do represent in this case the derivative of the OCV w.r.t. the temperature) were added for debug purposes, as they are used in the code for the model's equations.
