### ISSUE TITLE
Installing Sundials Solver in MATLAB

### ISSUE THREAD

**Issue by kimo707** [lionsimbatoolbox/LIONSIMBA#26]
Hii,
I am writing to seek your assistance regarding an issue I encountered while using the Lionsimbattoolbox that requires the installation of the IDA Sundials solver in MATLAB.

I have diligently searched the user guide of Sundials to find relevant information on the installation process, but unfortunately, I couldn't locate any specific details on how to install the solver in MATLAB. As this step is crucial for my work, I am reaching out to you for guidance and support.

I am aware that the Sundials package offers a MATLAB interface, but I'm unsure about the precise steps to enable it and successfully install the solver within the MATLAB environment. Given your expertise and knowledge in this area, I am hopeful that you can provide me with the necessary information or a step-by-step guide to complete the installation process correctly.

Thank you in advance for your time and consideration. I am grateful for any support you can extend to help me resolve this matter.

**Comment by lionsimbatoolbox** [comment]
Hello, I missed this comment. Are you still looking for help?

**Comment by Mrzhang-hub** [comment]
> Hello, I missed this comment. Are you still looking for help?

I have encounted the same problem, is there any tutorial for installing sundials for matlab in windows? My matlab version is 2021a. Hope you can give me some help, thanks.
