### ISSUE TITLE
install_STB.m error

### ISSUE THREAD

**Issue by sokratnak** [lionsimbatoolbox/LIONSIMBA#3]
I followed the installation instruction on Matlab R2017b academic but an error occurs: 
-----------------------
MEX files will be compiled and built using the above options
    Proceed? (y/n) y
Select modules to be built
Undefined function or variable 'cvm_ok'.
Error in install_STB (line 88)
if ~cvm_ok && ~idm_ok && ~kim_ok
------------------------

I am new to the toolbox, please advise.

**Comment by lionsimbatoolbox** [comment]
Hi,

the level of detail is quite low. It would be good to know additional information about the machine, and possible additional configurations that might produce some problem. However, I would strongly recommend you to read the latest user's manual to see whether you can solve the issues you are having.

**Comment by sokratnak** [comment]
Hi,
Thanks for getting back. 
I moved to another desktop a while ago and it works fine.

**Comment by dmahx4** [comment]
Hi,
  It seems to me that the install_STB.m file has totally varnished from the Sundial folders. I did appreciate any instruction on this.

**Comment by Raviiisc** [comment]
Unrecognized function or variable 'cvm_ok'. How should this error be corrected? I am using Matlab 2020b version.
