### ISSUE TITLE
Pouch cell -> cylindrical cell

### ISSUE THREAD

**Issue by mariapaygani** [lionsimbatoolbox/LIONSIMBA#5]
Dear developers,
greetings from Germany! My name is Maria and I have a question: 

a simulation of only pouch cell is possible or one can transform the model and suit it for, e. g. a cylindrical cell?

Thank you very much for your kind response and for the LIONSIMBA tool – it is a great pleasure to work with that! 

Best wishes

**Comment by lionsimbatoolbox** [comment]
Hello Maria,

thanks for the kind message!

Yes, you are right. If required, a simulation of a cylindrical cell would require a re-coding of the equations to account for the different geometry.

Vielen Dank und guten Abend :)
