### ISSUE TITLE
Ageing

### ISSUE THREAD

**Issue by mariapaygani** [lionsimbatoolbox/LIONSIMBA#6]
Hello dear friends,
I wanted to try out the ageing effects in the model, by setting the value 1 for the following parameter:

_%% Ageing parameters (TESTING PURPOSES, BETA VERSION)
param.EnableAgeing = 0;_

Unfortunately the programm will be stopped at the very beginning with the following comments in the command window:
Error using  .* 
Matrix dimensions must agree.

_Error in ionicFlux (line 41)
    eta_n   = (Phis(param.Np+1:end)-Phie(param.Np+param.Ns+1:end)-U_n
    -param.F*solverFlux(param.Np+1:end).*(param.R_SEI+film./(param.k_n_aging)));

Error in initialise_model (line 51)
jflux_init = ionicFlux(ce_init, cs_star, Phis_init, Phie_init, T, solverFlux, film, param,sign_input_density,I_density);

Error in startSimulation>mainCore (line 218)
    [~, n_alg(i), ~] = initialise_model(param{i});

Error in startSimulation (line 107)
results = mainCore(t0,tf,initialState,input_density,param);

Error in continous_custom_current_profile (line 51)
out = startSimulation(0,0.2,initialState,0,param);_

Does anyone know how to handle that?
How can one implement the aging in the model?

Thank you in advance!
Best wishes,
Maria

**Comment by lionsimbatoolbox** [comment]
Dear Maria,

thanks for the message!

There was a typo that has been fixed today in the code. Now everything works as expected.

**Comment by mariapaygani** [comment]
Hello dear authors,
unfortunately the error is not gone... It **comes out** for every script **as soon as I activate the ageing** and is gone as soon as I set the aging on zero..
Do you maybe know any other solutions?

Thank you very much
Greetings

**Comment by lionsimbatoolbox** [comment]
Hello Maria,

a new version of LIONSIMBA has been released. The problem shouldn't appear anymore.

Thanks
