### ISSUE TITLE
Octave Compability with Casadi

### ISSUE THREAD

**Issue by pasinger** [lionsimbatoolbox/LIONSIMBA#8]
The latest version of LIONSIMBA (2.0+) claims to have added support for Octave. However, I am running into issues that are seemingly related to the implementation of Casadi in Octave.
Has anyone been able to fully run LIONSIMBA in Octave? If so, any additional installation instructions would be really helpful. Things like which versions for Octave, Casadi, and Sundials would be particularly helpful (and what operating system you did this on).
I'm running from a 64-bit Windows PC.
Versions I've tried of the relevant software:
Casadi 3.4.4
Sundials 2.6.2
Octave 4.2.2 and 5.2

**Comment by lionsimbatoolbox** [comment]
Hi Patrick, I am able to run LIONSIMBA in Octave.

My setup is as follows (Linux machine):

- Octave 5.2.0
- Sundials 2.6.2
- Casadi 3.5.1

The "installation" process is exactly the same as for Matlab:

- Download and properly compile Sundials. Add the folder where sundials is installed to the Octave path
- Download Casadi (octave version) and unzip into a folder e.g.: Casadi somewhere on the PC. Make sure to addpath(genpath(aforementioned Casadi folder)) to the Octave path

You should be ready to run LIONSIMBA.

What error do you get?

**Comment by sameer9406** [comment]
Hi Patrick,

 I was able to install Casadi 3.5.1 successfully on Octave 5.2.0. I had faced troubles in installing sundials and Marcello had suggested me to install the mingw C++ compiler correctly. Its a bit complex process on the windows hence I gave up and using Matlab version on my linux sytem.

A Suggestion would be to check whether the C++ compiler is installed correctly.

Good luck,
Sameer

**Comment by lionsimbatoolbox** [comment]
Patrick, Sameer,

thanks for following-up.

I played around with the Windows installation and I was able to isolate an issue in relation to the running of the **install_STB.m** script.

In particular, there is an issue in relation to the definition of the paths that are declared in the script.

Specifically, Octave (under Windows) suffers of the following situation:

- **Not** working code

`mex -v 'C:\folder\folder2\test.c`

- **Working** code

`mex -v 'C:\\folder\\fodler2\\test.c`

Is therefore required to modify the parts of the **install_STB.m** script that takes care of this.

Search for **mex_cmd**  variable (which is the one that stores the entire compiling command) and apply a string replace following the above example.

It will work

**Comment by sameer9406** [comment]
Hi, 
Thank you for the solution. But I am not finding the path which you have described above.

Please can you upload the install_STB.m file that you have corrected. That will make it easier for me to see where exactly I have to change the code.

Thanks in advance

Regards,
Sameer

**Comment by sameer9406** [comment]
Hi,

I followed the updated instructions on the page and it worked amazingly well :)

Thank you
